name: tike_consumer
description: TIKE for Consumer .
author: CAPTURE Solutions
homepage: https://www.capturesolutions.com/

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  country_code_picker:
  country_pickers:
  bot_toast: ^3.0.5

  splashscreen:
  flutter_bloc: ^7.0.0
  equatable: ^2.0.2
  easy_localization:
  flutter_otp_text_field:
  sticky_grouped_list: ^1.3.0
  xml2json:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  flutter_screenutil: ^5.0.0+2
  carousel_slider: ^3.0.0
  url_launcher: ^6.0.4
  rxdart: any
  google_maps_flutter: ^0.5.11+1
    #  geoflutterfire: ^2.0.3+2
  location: ^2.3.5
  google_maps_webservice: ^0.0.14
  geolocator: any
  image_picker:
  scrollable_positioned_list: ^0.1.10
  fluttertoast: ^8.0.7
  intl: ^0.16.0
  path: ^1.8.0
  http_parser: ^4.0.0
  http: ^0.13.3
  google_fonts: ^2.1.0
  jiffy: ^3.0.1
  qr_flutter: ^4.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash:
  dynamic_theme:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/json/
    - assets/images/
    - assets/flags/
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: MontserratBlack
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
    - family: MontserratBlackItalic
      fonts:
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: MontserratMedium
      fonts:
          - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MontserratMediumItalic
      fonts:
          - asset: assets/fonts/Montserrat-MediumItalic.ttf
    - family: MontserratSemiBold
      fonts:
          - asset: assets/fonts/Montserrat-SemiBold.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
